#!/bin/tcsh
# your directory
cd /
cd /data1/AFNI/Projects/3T_piano/Subjects/Test
#data is where you copy the data too
# Make a directory where data is going to be analyzed: "new_piano_data"
mkdir new_piano_data -p
cd new_piano_data
# Make a directory for the monkey: "ramon"
mkdir ramon -p
cd ramon
# Make a directory for each session: "s1"
mkdir s1 -p
cd s1
# Make a directory for the localizer: "loc"
mkdir loc -p
cd loc
# Make a directory for the raw data: "raw"
mkdir raw -p
cd raw
# Now you have copy the data into loc 
# Note: the data inside the folder was already extracted using the following command inside the data folder: mv *.ACQ/*.IMA ./
#This is already done for the example data set
# In the real case you can do
#cp ../../../../data/1.3*/*.ACQ/*.IMA ./ 
# example data/ this should be your data set
#cp ../../../../../data/1.3*/*.ACQ/*~1.IMA ./
cp -r ../../../../../data/*.SER/*.ACQ ./
#---------------------------The special parameters for each run--------------------------
	set subj = 'ramon'
	set session = 's1'
	set runs = 'loc'
	set nt = '180'
	set nz = '25'
	set TR = '2.18sec'

#---------------------------Order files according to Simens format------------------------

	Dimon -GERT_Reco \
	-gert_nz 25 \
	-gert_to3d_prefix ${subj}.${session}.r${runs} \
	-infile_pattern '*ACQ/131221~1.IMA' \
#	-infile_pattern '*.IMA' \
	-gert_outdir ./ \
	-save_file_list dimon.files.${subj}.${session}.r${runs} \
	-dicom_org \
	-quit \
	-gert_filename ${subj}.${session}.r${runs} \
	-GERT_Reco

#---------------------------Load data------------------------------------------------------
	rm *+orig.*
	to3d \
	-prefix ${subj}.${session}.r${runs} \
	-orient RAS \
	-time:zt ${nz} ${nt} ${TR} alt+z \
	-assume_dicom_mosaic \
	-@ < dimon.files.${subj}.${session}.r${runs}

#---------------------------copy data------------------------------------------------------

	cp ${subj}.${session}.r${runs}+orig.* ../

#---------------------------Get stimulus log file----------------------------------

	cd ../
	cp ../../../../regresors/${subj}.${session}.r${runs}*.1D* ./

#--------------------------- Make stimulus times-------------------------------------------

	make_stim_times.py \
	-files ${subj}.${session}.r${runs}.1D \
	-prefix ${subj}.${session}.r${runs}.stimes \
	-tr 10.0 \
	-nruns 1 \
	-nt ${nt}

#--------------------------- Make stimulus times-------------------------------------------
cd /
cd /data1/AFNI/Projects/3T_piano/Subjects/Test/scripts/
./@prepro


		
